premiosApp/main/urls.py
from django.urls import path

from . import views


app_name = 'main'
urlpatterns = [
    #example: /main/
    path('', views.IndexView.as_view(), name='index'),
    #example: /main/id/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #example: /main/id/results
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #example: /main/id/vote
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

premiosApp/premiosApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]

premiosApp/main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

premiosApp/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


""" def index(request):
    latest_question_list = Question.objects.all()
    return render(request, 'main/index.html', {
        'latest_question_list': latest_question_list,
    })


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/detail.html', {
        'question': question,
    })


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {
        'question': question
    }) """
    

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return the last five published questions
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'
    
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'main/results.html'


def vote(request, question_id):
    # question = Question.objects.get(pk=1)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detail.html', {
            'question': question,
            'error_message': 'No elegiste una respuesta!'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))

premiosApp/main/templates/main/detail.html
<form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input 
                type="radio"
                name="choice"
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"
            >
            <label for="choice{{ forloop.counter }}">
                {{choice.choice_text}}
            </label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Votar">

</form>

<!-- <h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
      
    {% endfor %}
</ul> -->

premiosApp/main/templates/main/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'main:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

premiosApp/main/templates/main/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<p>¿Te gustaría botar de nuevo?</p>
<a href="{% url 'main:detail' question.id %}">Si, quiero votar de nuevo</a><br>
<a href="{% url 'main:index' %}">No, gracias</a>